apiVersion: apps/v1
kind: Deployment
metadata:
  name: sight-oracle-backend-sepolia-testnet
  namespace: default
  labels:
    app: sight-oracle-backend-sepolia-testnet
spec:
  replicas: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: sight-oracle-backend-sepolia-testnet
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: sight-oracle-backend-sepolia-testnet
    spec:
      containers:
        - name: sight-oracle-backend-sepolia-testnet
          image: gcr.io/celtic-descent-398803/sight-oracle-backend:0.0.1-sepolia
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "2"
              memory: 8Gi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
